services:
  frontend:
    build:
      context: ./build/docker/vue
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5757:8000"
    networks:
      - app-network

  backend:
    build:
      context: ./build/docker/python
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: note_app
      MYSQL_USER: note_user
      MYSQL_PASSWORD: note_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./build/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
